// A URL is a pointer to a resource and corresponds to the URI token in the
// grammar. It is generated by CSS parser when parsing URL values.
//  https://www.w3.org/TR/css3-values/#urls
import { PropertyValue } from "./property_value";
import { PropertyValueVisitor } from "./property_value_visitor";
import { NOTIMPLEMENTED } from "@neditor/core/base/common/notreached";
import { baseGetTypeId, TypeId } from "../base/type_id";

export class URLValue extends PropertyValue {
  private url_: string;
  // private is_absolute_: boolean;

  constructor(url: string) {
    super();
    this.url_ = url
  }
  Accept(visitor: PropertyValueVisitor): void {
    NOTIMPLEMENTED()
  }
  EQ(other: URLValue): boolean {
    return this.url_ === other.url_
  }
  GetTypeId(): TypeId {
    return baseGetTypeId(URLValue)
  }
  ToString(): string {
    return "url(" + this.url_ + ")"
  }
}
